# Generated by Django 2.0.5 on 2018-07-31 15:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0002_prediction_cluster_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_name', models.CharField(max_length=200)),
                ('battery_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('battery_tariff', models.CharField(max_length=15)),
                ('battery_customer_type', models.CharField(max_length=200)),
                ('deleted', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Centroids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_label', models.IntegerField()),
                ('tariff', models.CharField(max_length=15)),
                ('customer_type', models.CharField(max_length=200)),
                ('power', models.IntegerField()),
                ('consumption', models.CharField(max_length=200)),
                ('product_type', models.CharField(max_length=200)),
                ('cluster_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Financing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financing_name', models.CharField(max_length=200)),
                ('financing_monthly_interest', models.DecimalField(decimal_places=2, max_digits=10)),
                ('financing_month_duration', models.IntegerField()),
                ('deleted', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_name', models.CharField(max_length=200)),
                ('insurance_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insurance_level', models.IntegerField()),
                ('deleted', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_name', models.CharField(max_length=200)),
                ('maintenance_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maintenance_level', models.IntegerField()),
                ('deleted', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_name', models.CharField(max_length=200)),
                ('manager_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('manager_tariff', models.CharField(max_length=15)),
                ('manager_customer_type', models.CharField(max_length=200)),
                ('deleted', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Smarthome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smarthome_name', models.CharField(max_length=200)),
                ('smarthome_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('smarthome_tariff', models.CharField(max_length=15)),
                ('smarthome_customer_type', models.CharField(max_length=200)),
                ('deleted', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=200)),
                ('vehicle_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicle_tariff', models.CharField(max_length=15)),
                ('vehicle_power', models.IntegerField()),
                ('deleted', models.IntegerField(default=0)),
            ],
        ),
    ]
