# Generated by Django 2.0.5 on 2018-08-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0006_auto_20180801_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smarthome',
            name='smarthome_price',
        ),
        migrations.AddField(
            model_name='smarthome',
            name='smarthome_max_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='smarthome',
            name='smarthome_min_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
