# Generated by Django 2.0.5 on 2018-08-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0007_auto_20180801_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='costs',
            name='cost_tariff',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
