# Generated by Django 2.0.5 on 2018-08-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0008_costs_cost_tariff'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='insurance_customer_type',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='insurance',
            name='insurance_tariff',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='maintenance_customer_type',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='maintenance_tariff',
            field=models.CharField(default='', max_length=15),
        ),
    ]
