CREATE TABLE public.surveys_choice_v1
(
    id integer,
    choice_text varchar(200),
    votes integer,
    question_id integer
);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (1, 'Menor de 10 kW', 0, 2);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (2, 'Entre 10 y 15 kW', 0, 2);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (3, 'Entre 15 y 450 kW', 0, 2);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (4, 'Mayor de 450 kW', 0, 2);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (5, 'Precio fijo anual', 0, 3);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (6, 'Precio indexado al Mercado Eléctrico', 0, 3);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (7, 'Transferencia bancária', 0, 5);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (8, 'Domiciliada', 0, 5);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (9, 'Sí', 0, 6);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (10, 'No', 0, 6);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (11, 'No se', 0, 6);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (12, 'Hogar', 0, 7);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (13, 'Empresa', 0, 7);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (14, 'Administración pública', 0, 7);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (15, '2.0 A', 0, 8);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (16, '2.0 DHA', 0, 8);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (17, '2.1 A', 0, 8);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (18, '2.1 DHA', 0, 8);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (19, '3.0 A', 0, 8);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (20, '3.1 A', 0, 8);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (21, '6.1 A', 0, 8);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (22, 'Otros', 0, 8);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (23, 'Vehículo eléctrico', 0, 9);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (24, 'Smart home', 0, 9);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (25, 'Otros', 0, 9);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (26, 'Sí', 0, 10);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (27, 'No', 0, 10);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (28, 'Tal vez', 0, 10);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (29, 'Sí', 0, 11);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (30, 'No', 0, 11);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (31, 'Sí', 0, 12);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (32, 'No', 0, 12);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (33, 'Tal vez', 0, 12);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (34, '1 (cobertura mínima)', 0, 13);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (35, '2', 0, 13);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (36, '3', 0, 13);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (37, '4', 0, 13);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (38, '5 (cobertura máxima)', 0, 13);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (39, 'Sí', 0, 14);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (40, 'No', 0, 14);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (41, 'Sí', 0, 15);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (42, 'No', 0, 15);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (43, '1 (Muy poco importante)', 0, 16);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (44, '2', 0, 16);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (45, '3', 0, 16);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (46, '4', 0, 16);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (47, '5 (Lo más importante)', 0, 16);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (48, '1 (Muy poco importante)', 0, 17);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (49, '2', 0, 17);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (50, '3', 0, 17);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (51, '4', 0, 17);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (52, '5 (Lo más importante)', 0, 17);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (53, '1 (Muy poco importante)', 0, 18);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (54, '2', 0, 18);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (55, '3', 0, 18);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (56, '4', 0, 18);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (57, '5 (Lo más importante)', 0, 18);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (58, '1 (Me resulta indiferente)', 0, 19);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (59, '2', 0, 19);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (60, '3', 0, 19);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (61, '4', 0, 19);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (62, '5 (Es muy relevante para mi)', 0, 19);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (63, 'Prefiero un precio más alto y no tener permanencia.', 0, 20);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (64, 'No me importa si eso implica conseguir un precio más barato.', 0, 20);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (65, 'Otros', 0, 20);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (66, '1 (No me interesa para nada)', 0, 21);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (67, '2', 0, 21);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (68, '3', 0, 21);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (69, '4', 0, 21);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (70, '5 (Me encantaría)', 0, 21);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (71, '1 (Nada)', 0, 22);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (72, '2', 0, 22);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (73, '3', 0, 22);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (74, '4', 0, 22);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (75, '5 (El máximo a cambio de la máxima calidad)', 0, 22);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (76, 'Sí', 0, 23);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (77, 'No', 0, 23);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (78, 'Tal vez', 0, 23);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (79, 'Sí', 0, 24);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (80, 'No', 0, 24);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (81, 'Tal vez', 0, 24);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (82, '1 (Nada)', 0, 25);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (83, '2', 0, 25);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (84, '3', 1, 25);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (85, '4', 0, 25);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (86, '5 (El máximo a cambio de olvidarme de cualquier gestión)', 0, 25);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (87, 'Sí', 0, 26);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (88, 'No', 0, 26);
INSERT INTO public.surveys_choice_v1 (id, choice_text, votes, question_id) VALUES (89, 'Tal vez', 0, 26);