select * from cluster_maintenance;
INSERT INTO cluster_maintenance(maintenance_name, maintenance_price, maintenance_level,maintenance_customer_type,maintenance_tariff, deleted) VALUES ('Factor Luz Gratuito',0,1,'Domestico','2.0 A',0);
INSERT INTO cluster_maintenance(maintenance_name, maintenance_price, maintenance_level,maintenance_customer_type,maintenance_tariff, deleted) VALUES ('Factor Luz Gratuito',0,1,'Domestico','2.0 DHA',0);
INSERT INTO cluster_maintenance(maintenance_name, maintenance_price, maintenance_level,maintenance_customer_type,maintenance_tariff, deleted) VALUES ('Factor Luz Gratuito',0,1,'Domestico','2.0 DHS',0);
INSERT INTO cluster_maintenance(maintenance_name, maintenance_price, maintenance_level,maintenance_customer_type,maintenance_tariff, deleted) VALUES ('Factor Luz',8.89,2,'Domestico','2.1 A',0);
INSERT INTO cluster_maintenance(maintenance_name, maintenance_price, maintenance_level,maintenance_customer_type,maintenance_tariff, deleted) VALUES ('Factor Luz',8.89,2,'Domestico','2.1 DHA',0);
INSERT INTO cluster_maintenance(maintenance_name, maintenance_price, maintenance_level,maintenance_customer_type,maintenance_tariff, deleted) VALUES ('Factor Luz',8.89,2,'Domestico','2.1 DHS',0);
INSERT INTO cluster_maintenance(maintenance_name, maintenance_price, maintenance_level,maintenance_customer_type,maintenance_tariff, deleted) VALUES ('Hogar Confort',14.17,4,'Domestico','3.0 A',0);
INSERT INTO cluster_maintenance(maintenance_name, maintenance_price, maintenance_level,maintenance_customer_type,maintenance_tariff, deleted) VALUES ('Hogar Premium',18.53,4,'Domestico','3.1 A',0);
INSERT INTO cluster_maintenance(maintenance_name, maintenance_price, maintenance_level,maintenance_customer_type,maintenance_tariff, deleted) VALUES ('Premium',40.89,5,'Domestico','6.1 A',0);
INSERT INTO cluster_maintenance(maintenance_name, maintenance_price, maintenance_level,maintenance_customer_type,maintenance_tariff, deleted) VALUES ('Premium',50.24,5,'Domestico','X',0);
