# Generated by Django 2.0.5 on 2018-06-06 12:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='insert_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='user_answers_datetime_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
