# Generated by Django 2.0.5 on 2018-06-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_auto_20180606_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='user_answers_datetime_id',
        ),
        migrations.AddField(
            model_name='answer',
            name='form_token',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
