# Generated by Django 2.0.5 on 2018-07-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_auto_20180607_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='training_set',
            field=models.IntegerField(default=0),
        ),
    ]
