# Generated by Django 2.0.5 on 2018-08-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_answer_training_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translate_Hired_Power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hired_power_literal', models.CharField(max_length=200)),
                ('min_hired_power', models.IntegerField(default=0)),
                ('max_hired_power', models.IntegerField(default=800)),
                ('deleted', models.IntegerField(default=0)),
            ],
        ),
    ]
